# Site settings
title: Lacourse Design Co. | Websites & Web Apps
email: mikelacourse@gmail.com
description: >
  We’re a small design shop based in Portland, Maine that’s big on craftsmenship. From branding to design to coding, we do it right.
baseurl: ""
url: "http://www.lacourse.co"
github_username:  cupcakedream

# Build settings
markdown: kramdown
